### ISSUE TITLE
how to define persistence using XML metadata and mark which are persistable

### ISSUE THREAD

**Issue by cloudSher** [datanucleus/tests#9]
In the JDO Tutorial, I define persistence using XML metadata,but the classes have not enhanced,
[jdo tutorial](http://www.datanucleus.org/products/accessplatform/jdo/samples/tutorial_rdbms.html)

this is example:
`@PersistenceCapable
public class Product
{
//    @PrimaryKey
//    @Persistent(valueStrategy=IdGeneratorStrategy.NATIVE)
    protected long id;

    protected String name=null;

    protected String description=null;

    protected double price=0.0;

    public Product(String name, String description, double price)
    {
        this.name = name;
        this.description = description;
        this.price = price;
    }

    public long getId()
    {
        return id;
    }

    public String getName()
    {
        return name;
    }

    public String getDescription()
    {
        return description;
    }

    public double getPrice()
    {
        return price;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public void setPrice(double price)
    {
        this.price = price;
    }

    public String toString()
    {
        return "Product : " + id + " name=" + name + " [" + description + "]";
    }
}`

like this, run successed, but I remove the “@PersistenceCapable” annotation,
how to define model classes using xml metadata?

In the sample project, I define **package.jdo** in resource like this:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jdo PUBLIC
    "-//Sun Microsystems, Inc.//DTD Java Data Objects Metadata 2.0//EN"
    "http://java.sun.com/dtd/jdo_2_0.dtd">
<orm>
    <package name="org.datanucleus.samples.jdo.tutorial">
        <class name="Inventory"   persistence-modifier="persistence-capable">
            <field name="name"></field>
            <field name="products"/>
        </class>

        <class name="Product"   persistence-modifier="persistence-capable">
            <field name="id" />
            <field name="name" />
            <field name="description"/>
            <field name="price"/>
        </class>
    </package>
</orm>`

using maven plugin 
`mvn datanucleus:enhance`
result:
`[INFO] DataNucleus Enhancer (version 5.0.1) for API "JDO"
DataNucleus Enhancer completed with success for 0 classes.
DataNucleus Enhancer completed and no classes were enhanced. Consult the log for full details`

no classes were enhanced,so how to define persistence only using xml metadata?

**Comment by andyjefferson** [comment]
This is the testsuite for DataNucleus. It is not the place for questions/problems. Use the forum or Stackoverflow for that.
